#
FROM python:3.11.5

#
WORKDIR /fastapi

COPY requirements.txt ./

# Copy the .env file into the container
COPY .env .

#
RUN pip install --no-cache-dir -r requirements.txt

#
COPY . .

#
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]